modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Prismwork/EMITrades/issues"
license = "MIT"

[[mods]]
modId = "emitrades"
version = "${version}"
displayName = "EMI Trades"
authors = "Flamarine"
description = '''
Villager trades for EMI.
'''
logoFile = "icon.png"

[[dependencies.emitrades]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emitrades]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emitrades]]
modId = "emi"
mandatory = true
versionRange = "[1.0,)"
ordering = "NONE"
side = "CLIENT"
