modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Prismwork/EMITrades/issues"
license = "MIT"

[[mods]]
modId = "emitrades"
version = "${version}"
displayName = "EMI Trades"
authors = "Prismwork, Flamarine"
description = '''
Villager trades for EMI.
'''
logoFile = "icon.png"

[[dependencies.emitrades]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[20.4.72-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emitrades]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emitrades]]
modId = "emi"
type = "REQUIRED"
versionRange = "[1.0,)"
ordering = "NONE"
side = "CLIENT"
